/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type RowImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "row.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: 'image';
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
};

export type FileAttachmentFile = {
  asset?: SanityFileAssetReference;
  media?: unknown; // Unable to locate the referenced type "file.media" in schema
  _type: 'file';
};

export type SignupSheetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'signupSheet';
};

export type SignupEntry = {
  _id: string;
  _type: 'signupEntry';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sheet?: SignupSheetReference;
  slotKey?: string;
  slotLabel?: string;
  familyName?: string;
  note?: string;
  submittedAt?: string;
};

export type TeacherNote = {
  _id: string;
  _type: 'teacherNote';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  class?: 'twos' | 'threes' | 'pre-k';
  active?: boolean;
  version?: string;
  heading?: string;
  dateLabel?: string;
  salutation?: string;
  body?: BlockContent;
  signName?: string;
  signRole?: string;
  email?: string;
  phone?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: 'span';
    _key: string;
  }>;
  style?: 'normal' | 'h3' | 'h4' | 'blockquote';
  listItem?: 'bullet' | 'number';
  markDefs?: Array<{
    href?: string;
    _type: 'link';
    _key: string;
  }>;
  level?: number;
  _type: 'block';
  _key: string;
}>;

export type HubDocument = {
  _id: string;
  _type: 'hubDocument';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  category?: 'required' | 'handbook' | 'orient' | 'minutes';
  description?: string;
  icon?:
    | 'arrow-right'
    | 'award'
    | 'baby'
    | 'scale'
    | 'bell'
    | 'building-2'
    | 'blocks'
    | 'cake'
    | 'calculator'
    | 'calendar-days'
    | 'camera'
    | 'hand-heart'
    | 'banknote'
    | 'file-check'
    | 'check'
    | 'clipboard-list'
    | 'clock'
    | 'coins'
    | 'contact'
    | 'file-text'
    | 'circle-dollar-sign'
    | 'dumbbell'
    | 'egg'
    | 'mail'
    | 'eye'
    | 'file-pen'
    | 'flower'
    | 'folder'
    | 'gift'
    | 'graduation-cap'
    | 'hand'
    | 'heart-handshake'
    | 'heart'
    | 'heart-pulse'
    | 'house'
    | 'info'
    | 'languages'
    | 'leaf'
    | 'list'
    | 'lock'
    | 'map-pin'
    | 'megaphone'
    | 'microscope'
    | 'moon'
    | 'newspaper'
    | 'notebook-pen'
    | 'book-open'
    | 'door-open'
    | 'folder-open'
    | 'palette'
    | 'send'
    | 'party-popper'
    | 'pencil'
    | 'users'
    | 'phone'
    | 'image'
    | 'piggy-bank'
    | 'puzzle'
    | 'school'
    | 'shield-check'
    | 'shopping-bag'
    | 'snowflake'
    | 'sparkles'
    | 'message-circle'
    | 'sprout'
    | 'star'
    | 'sun'
    | 'tent'
    | 'trees'
    | 'trending-down';
  sourceType?: 'link' | 'file';
  link?: string;
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: 'file';
  };
  order?: number;
  orderRank?: string;
};

export type Celebration = {
  _id: string;
  _type: 'celebration';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  kind?: 'birthday' | 'kudos' | 'welcome' | 'milestone';
  headline?: string;
  note?: string;
  date?: string;
};

export type Update = {
  _id: string;
  _type: 'update';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  publishedAt?: string;
  pinned?: boolean;
  highlight?: boolean;
  showUntil?: string;
  category?: 'announcement' | 'minutes';
  audience?: string;
  body?: PostBody;
};

export type EventReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'event';
};

export type PostBody = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h2' | 'h3' | 'blockquote';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: 'image';
      _key: string;
    }
  | {
      tone?: 'sky' | 'warm';
      text?: string;
      _type: 'calloutBlock';
      _key: string;
    }
  | {
      label?: string;
      url?: string;
      _type: 'buttonBlock';
      _key: string;
    }
  | {
      sheet?: SignupSheetReference;
      _type: 'signupCard';
      _key: string;
    }
  | {
      event?: EventReference;
      _type: 'eventCard';
      _key: string;
    }
  | {
      headerRow?: boolean;
      rows?: Array<{
        cells?: Array<string>;
        _type: 'tableRow';
        _key: string;
      }>;
      _type: 'tableBlock';
      _key: string;
    }
  | {
      left?: BlockContent;
      right?: BlockContent;
      _type: 'twoColumns';
      _key: string;
    }
  | {
      url?: string;
      title?: string;
      _type: 'videoEmbed';
      _key: string;
    }
  | {
      images?: Array<{
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: 'image';
        _key: string;
      }>;
      _type: 'postGallery';
      _key: string;
    }
  | {
      file?: FileAttachmentFile;
      title?: string;
      _type: 'fileAttachment';
      _key: string;
    }
>;

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type Resource = {
  _id: string;
  _type: 'resource';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  category?: 'handbook' | 'calendar' | 'forms' | 'other';
  description?: string;
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: 'file';
  };
  url?: string;
  orderRank?: string;
};

export type JobPosting = {
  _id: string;
  _type: 'jobPosting';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  active?: boolean;
  type?: 'teaching' | 'board' | 'other';
  summary?: string;
  body?: RichProse;
  applyUrl?: string;
  orderRank?: string;
};

export type RichProse = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: 'span';
    _key: string;
  }>;
  style?: 'normal' | 'h2' | 'h3' | 'blockquote';
  listItem?: 'bullet' | 'number';
  markDefs?: Array<{
    href?: string;
    _type: 'link';
    _key: string;
  }>;
  level?: number;
  _type: 'block';
  _key: string;
}>;

export type Campaign = {
  _id: string;
  _type: 'campaign';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  active?: boolean;
  summary?: string;
  goalAmount?: number;
  raisedAmount?: number;
  deadline?: string;
  linkLabel?: string;
  linkUrl?: string;
};

export type Credential = {
  _id: string;
  _type: 'credential';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  logo?: FigureImage;
  url?: string;
  orderRank?: string;
};

export type FigureImage = {
  _type: 'figureImage';
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  alt?: string;
  caption?: string;
};

export type Partner = {
  _id: string;
  _type: 'partner';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  logo?: FigureImage;
  url?: string;
  orderRank?: string;
};

export type BoardMember = {
  _id: string;
  _type: 'boardMember';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  bio?: string;
  photo?: FigureImage;
  email?: string;
  orderRank?: string;
};

export type Program = {
  _id: string;
  _type: 'program';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  icon?:
    | 'arrow-right'
    | 'award'
    | 'baby'
    | 'scale'
    | 'bell'
    | 'building-2'
    | 'blocks'
    | 'cake'
    | 'calculator'
    | 'calendar-days'
    | 'camera'
    | 'hand-heart'
    | 'banknote'
    | 'file-check'
    | 'check'
    | 'clipboard-list'
    | 'clock'
    | 'coins'
    | 'contact'
    | 'file-text'
    | 'circle-dollar-sign'
    | 'dumbbell'
    | 'egg'
    | 'mail'
    | 'eye'
    | 'file-pen'
    | 'flower'
    | 'folder'
    | 'gift'
    | 'graduation-cap'
    | 'hand'
    | 'heart-handshake'
    | 'heart'
    | 'heart-pulse'
    | 'house'
    | 'info'
    | 'languages'
    | 'leaf'
    | 'list'
    | 'lock'
    | 'map-pin'
    | 'megaphone'
    | 'microscope'
    | 'moon'
    | 'newspaper'
    | 'notebook-pen'
    | 'book-open'
    | 'door-open'
    | 'folder-open'
    | 'palette'
    | 'send'
    | 'party-popper'
    | 'pencil'
    | 'users'
    | 'phone'
    | 'image'
    | 'piggy-bank'
    | 'puzzle'
    | 'school'
    | 'shield-check'
    | 'shopping-bag'
    | 'snowflake'
    | 'sparkles'
    | 'message-circle'
    | 'sprout'
    | 'star'
    | 'sun'
    | 'tent'
    | 'trees'
    | 'trending-down';
  ageRange?: string;
  schedule?: string;
  summary?: string;
  image?: FigureImage;
  orderRank?: string;
};

export type HoursLog = {
  _id: string;
  _type: 'hoursLog';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  familyName?: string;
  hours?: number;
  category?: 'classroom' | 'cleaning' | 'event' | 'committee' | 'donation' | 'other';
  activity?: string;
  date?: string;
  verified?: boolean;
  source?: 'self' | 'board';
  submittedAt?: string;
};

export type DirectoryEntryReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'directoryEntry';
};

export type RoleHolder = {
  _id: string;
  _type: 'roleHolder';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  role?:
    | 'President'
    | 'Vice President'
    | 'Treasurer'
    | 'Secretary'
    | 'Teacher \u2014 Pre-K'
    | 'Teacher \u2014 Twos & Threes'
    | 'Administrator'
    | 'Publicity Chair'
    | 'Enrichment Coordinator'
    | 'Copy Room Helper'
    | 'Facilities Chair'
    | 'Family Activities Chair'
    | 'Fundraising Chair'
    | 'Twos Rep'
    | 'Threes Rep'
    | 'Pre-K AM Rep'
    | 'Pre-K PM Rep';
  person?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  email?: string;
  contactFrom?: DirectoryEntryReference;
  note?: string;
};

export type DirectoryEntry = {
  _id: string;
  _type: 'directoryEntry';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  familyName?: string;
  optedIn?: boolean;
  parents?: Array<{
    name?: string;
    role?: string;
    email?: string;
    phone?: string;
    _key: string;
  }>;
  children?: Array<{
    name?: string;
    class?: string;
    _key: string;
  }>;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  address?: string;
  location?: Geopoint;
  notes?: string;
  neighborhood?: string;
  carpoolInterest?: boolean;
  playdateInterest?: boolean;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type CoopRole = {
  _id: string;
  _type: 'coopRole';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  tier?: 'board' | 'chairs' | 'reps' | 'committee';
  icon?:
    | 'arrow-right'
    | 'award'
    | 'baby'
    | 'scale'
    | 'bell'
    | 'building-2'
    | 'blocks'
    | 'cake'
    | 'calculator'
    | 'calendar-days'
    | 'camera'
    | 'hand-heart'
    | 'banknote'
    | 'file-check'
    | 'check'
    | 'clipboard-list'
    | 'clock'
    | 'coins'
    | 'contact'
    | 'file-text'
    | 'circle-dollar-sign'
    | 'dumbbell'
    | 'egg'
    | 'mail'
    | 'eye'
    | 'file-pen'
    | 'flower'
    | 'folder'
    | 'gift'
    | 'graduation-cap'
    | 'hand'
    | 'heart-handshake'
    | 'heart'
    | 'heart-pulse'
    | 'house'
    | 'info'
    | 'languages'
    | 'leaf'
    | 'list'
    | 'lock'
    | 'map-pin'
    | 'megaphone'
    | 'microscope'
    | 'moon'
    | 'newspaper'
    | 'notebook-pen'
    | 'book-open'
    | 'door-open'
    | 'folder-open'
    | 'palette'
    | 'send'
    | 'party-popper'
    | 'pencil'
    | 'users'
    | 'phone'
    | 'image'
    | 'piggy-bank'
    | 'puzzle'
    | 'school'
    | 'shield-check'
    | 'shopping-bag'
    | 'snowflake'
    | 'sparkles'
    | 'message-circle'
    | 'sprout'
    | 'star'
    | 'sun'
    | 'tent'
    | 'trees'
    | 'trending-down';
  team?: string;
  reportsTo?: string;
  stipend?: string;
  body?: string;
  order?: number;
  orderRank?: string;
};

export type TrashedItem = {
  _id: string;
  _type: 'trashedItem';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  originalType?: string;
  deletedAt?: string;
  originalId?: string;
  payload?: string;
};

export type PhotoSubmission = {
  _id: string;
  _type: 'photoSubmission';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  caption?: string;
  submittedBy?: string;
  approved?: boolean;
  submittedAt?: string;
};

export type TestimonialSubmission = {
  _id: string;
  _type: 'testimonialSubmission';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: string;
  authorName?: string;
  connection?: string;
  email?: string;
  permission?: boolean;
  submittedAt?: string;
  handled?: boolean;
};

export type Subscriber = {
  _id: string;
  _type: 'subscriber';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  name?: string;
  source?: string;
  subscribedAt?: string;
};

export type Submission = {
  _id: string;
  _type: 'submission';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  phone?: string;
  topic?: string;
  message?: string;
  pageUrl?: string;
  submittedAt?: string;
  handled?: boolean;
};

export type PageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'page';
};

export type Announcement = {
  _id: string;
  _type: 'announcement';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  format?: 'bar' | 'popup';
  template?: 'custom' | 'waitlist' | 'event' | 'fundraiser' | 'notice' | 'welcome';
  message?: string;
  tone?: 'info' | 'good' | 'warning' | 'urgent' | 'brand';
  icon?:
    | 'arrow-right'
    | 'award'
    | 'baby'
    | 'scale'
    | 'bell'
    | 'building-2'
    | 'blocks'
    | 'cake'
    | 'calculator'
    | 'calendar-days'
    | 'camera'
    | 'hand-heart'
    | 'banknote'
    | 'file-check'
    | 'check'
    | 'clipboard-list'
    | 'clock'
    | 'coins'
    | 'contact'
    | 'file-text'
    | 'circle-dollar-sign'
    | 'dumbbell'
    | 'egg'
    | 'mail'
    | 'eye'
    | 'file-pen'
    | 'flower'
    | 'folder'
    | 'gift'
    | 'graduation-cap'
    | 'hand'
    | 'heart-handshake'
    | 'heart'
    | 'heart-pulse'
    | 'house'
    | 'info'
    | 'languages'
    | 'leaf'
    | 'list'
    | 'lock'
    | 'map-pin'
    | 'megaphone'
    | 'microscope'
    | 'moon'
    | 'newspaper'
    | 'notebook-pen'
    | 'book-open'
    | 'door-open'
    | 'folder-open'
    | 'palette'
    | 'send'
    | 'party-popper'
    | 'pencil'
    | 'users'
    | 'phone'
    | 'image'
    | 'piggy-bank'
    | 'puzzle'
    | 'school'
    | 'shield-check'
    | 'shopping-bag'
    | 'snowflake'
    | 'sparkles'
    | 'message-circle'
    | 'sprout'
    | 'star'
    | 'sun'
    | 'tent'
    | 'trees'
    | 'trending-down';
  linkLabel?: string;
  linkType?: 'page' | 'url';
  page?: PageReference;
  url?: string;
  enabled?: boolean;
  showFrom?: string;
  showUntil?: string;
  priority?: number;
  placement?: 'all' | 'only' | 'except';
  pages?: Array<
    {
      _key: string;
    } & PageReference
  >;
  frequency?: 'once' | 'session' | 'always';
  version?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heading?: string;
};

export type Redirect = {
  _id: string;
  _type: 'redirect';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  from?: string;
  to?: string;
  permanent?: boolean;
  note?: string;
};

export type NewsletterIssue = {
  _id: string;
  _type: 'newsletterIssue';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  preheader?: string;
  coverImage?: FigureImage;
  body?: PostBody;
  emailedAt?: string;
  seoDescription?: string;
  ogImage?: FigureImage;
};

export type StaffReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'staff';
};

export type Post = {
  _id: string;
  _type: 'post';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  category?: 'news' | 'announcements' | 'events' | 'learning';
  author?: StaffReference;
  coverImage?: FigureImage;
  excerpt?: string;
  body?: PostBody;
  seoTitle?: string;
  seoDescription?: string;
  ogImage?: FigureImage;
};

export type SectionPreset = {
  _id: string;
  _type: 'sectionPreset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  sectionType?: string;
  section?: Array<
    | ({
        _key: string;
      } & ProseSection)
    | ({
        _key: string;
      } & CardGridSection)
    | ({
        _key: string;
      } & StatBandSection)
    | ({
        _key: string;
      } & CtaSection)
    | ({
        _key: string;
      } & TestimonialSection)
    | ({
        _key: string;
      } & TeacherSection)
    | ({
        _key: string;
      } & ClassCardsSection)
    | ({
        _key: string;
      } & FaqSection)
    | ({
        _key: string;
      } & SchoolYearSection)
    | ({
        _key: string;
      } & TuitionTableSection)
    | ({
        _key: string;
      } & TuitionCalculatorSection)
    | ({
        _key: string;
      } & EnrollmentCtaSection)
    | ({
        _key: string;
      } & ScheduleSection)
    | ({
        _key: string;
      } & StepListSection)
    | ({
        _key: string;
      } & CompareSection)
    | ({
        _key: string;
      } & TabsSection)
    | ({
        _key: string;
      } & AccordionSection)
    | ({
        _key: string;
      } & QuickFactsSection)
    | ({
        _key: string;
      } & PullQuoteSection)
    | ({
        _key: string;
      } & VideoSection)
    | ({
        _key: string;
      } & MapSection)
    | ({
        _key: string;
      } & CountdownSection)
    | ({
        _key: string;
      } & GallerySection)
    | ({
        _key: string;
      } & StoryTimelineSection)
    | ({
        _key: string;
      } & SplitMediaSection)
    | ({
        _key: string;
      } & LatestPostsSection)
    | ({
        _key: string;
      } & UpcomingEventsSection)
    | ({
        _key: string;
      } & FormSection)
    | ({
        _key: string;
      } & NewsletterSignupSection)
    | ({
        _key: string;
      } & ReviewFormSection)
    | ({
        _key: string;
      } & NoticeBarSection)
    | ({
        _key: string;
      } & ContactDetailsSection)
    | ({
        _key: string;
      } & ProgramCardsSection)
    | ({
        _key: string;
      } & BoardMembersSection)
    | ({
        _key: string;
      } & LogoStripSection)
    | ({
        _key: string;
      } & CampaignSection)
    | ({
        _key: string;
      } & JobsSection)
    | ({
        _key: string;
      } & DownloadsSection)
    | ({
        _key: string;
      } & AlbumSection)
    | ({
        _key: string;
      } & InstagramSection)
  >;
  note?: string;
};

export type LegalPage = {
  _id: string;
  _type: 'legalPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: 'accessibility' | 'privacy' | 'terms';
  eyebrow?: string;
  lead?: string;
  body?: BlockContent;
  lastUpdated?: string;
};

export type SchoolYearEvent = {
  _id: string;
  _type: 'schoolYearEvent';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  month?: string;
  body?: string;
  icon?:
    | 'arrow-right'
    | 'award'
    | 'baby'
    | 'scale'
    | 'bell'
    | 'building-2'
    | 'blocks'
    | 'cake'
    | 'calculator'
    | 'calendar-days'
    | 'camera'
    | 'hand-heart'
    | 'banknote'
    | 'file-check'
    | 'check'
    | 'clipboard-list'
    | 'clock'
    | 'coins'
    | 'contact'
    | 'file-text'
    | 'circle-dollar-sign'
    | 'dumbbell'
    | 'egg'
    | 'mail'
    | 'eye'
    | 'file-pen'
    | 'flower'
    | 'folder'
    | 'gift'
    | 'graduation-cap'
    | 'hand'
    | 'heart-handshake'
    | 'heart'
    | 'heart-pulse'
    | 'house'
    | 'info'
    | 'languages'
    | 'leaf'
    | 'list'
    | 'lock'
    | 'map-pin'
    | 'megaphone'
    | 'microscope'
    | 'moon'
    | 'newspaper'
    | 'notebook-pen'
    | 'book-open'
    | 'door-open'
    | 'folder-open'
    | 'palette'
    | 'send'
    | 'party-popper'
    | 'pencil'
    | 'users'
    | 'phone'
    | 'image'
    | 'piggy-bank'
    | 'puzzle'
    | 'school'
    | 'shield-check'
    | 'shopping-bag'
    | 'snowflake'
    | 'sparkles'
    | 'message-circle'
    | 'sprout'
    | 'star'
    | 'sun'
    | 'tent'
    | 'trees'
    | 'trending-down';
  accent?: 'amber' | 'green' | 'orange' | 'sky' | 'navy';
  order?: number;
  orderRank?: string;
};

export type FaqItem = {
  _id: string;
  _type: 'faqItem';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: BlockContent;
  category?: 'coop' | 'classes' | 'enrollment' | 'about' | 'donation';
  order?: number;
  orderRank?: string;
};

export type Testimonial = {
  _id: string;
  _type: 'testimonial';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: string;
  author?: string;
  role?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  tags?: Array<string>;
  featured?: boolean;
  order?: number;
  orderRank?: string;
};

export type Class = {
  _id: string;
  _type: 'class';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  icon?: string;
  color?: 'amber' | 'green' | 'orange' | 'sky' | 'navy';
  tagline?: string;
  teacher?: StaffReference;
  helperScheduleUrl?: string;
  photoAlbumUrl?: string;
  days?: string;
  daysCount?: string;
  time?: string;
  age?: string;
  classSizeCap?: number;
  dailySchedule?: Array<{
    time?: string;
    title?: string;
    description?: string;
    _key: string;
  }>;
  monthly?: string;
  annual?: string;
  studentFee?: string;
  payId?: string;
  studentFeePayId?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  whatTheyLearn?: Array<
    {
      _key: string;
    } & IconCard
  >;
  order?: number;
  orderRank?: string;
};

export type Staff = {
  _id: string;
  _type: 'staff';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  honorific?: string;
  role?: string;
  years?: string;
  email?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  pullQuote?: string;
  bio?: BlockContent;
  order?: number;
};

export type PresidentNote = {
  _id: string;
  _type: 'presidentNote';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  active?: boolean;
  version?: string;
  heading?: string;
  dateLabel?: string;
  salutation?: string;
  body?: BlockContent;
  signName?: string;
  signRole?: string;
  email?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type ClosureAlert = {
  _id: string;
  _type: 'closureAlert';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  active?: boolean;
  message?: string;
  tone?: 'info' | 'warning' | 'urgent';
  linkLabel?: string;
  linkUrl?: string;
};

export type Navigation = {
  _id: string;
  _type: 'navigation';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  mainNav?: Array<
    | ({
        _key: string;
      } & NavLink)
    | ({
        _key: string;
      } & NavGroup)
  >;
  headerCta?: {
    show?: boolean;
    label?: string;
    linkType?: 'page' | 'url';
    page?: PageReference;
    url?: string;
  };
  footerColumns?: Array<{
    label?: string;
    links?: Array<
      {
        _key: string;
      } & NavLink
    >;
    _type: 'footerColumn';
    _key: string;
  }>;
  legalNav?: Array<
    {
      _key: string;
    } & NavLink
  >;
};

export type SupplyList = {
  _id: string;
  _type: 'supplyList';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  year?: string;
  backpackNote?: string;
  dueNote?: string;
  waterNote?: string;
  lists?: Array<{
    slug?: 'twos' | 'threes' | 'pre-k-am' | 'pre-k-pm';
    items?: Array<string>;
    _key: string;
  }>;
  wishList?: {
    heading?: string;
    note?: string;
    items?: Array<string>;
  };
};

export type CurriculumGuide = {
  _id: string;
  _type: 'curriculumGuide';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  class?: 'twos' | 'threes' | 'pre-k';
  kicker?: string;
  title?: string;
  intro?: string;
  sections?: Array<{
    icon?: string;
    title?: string;
    items?: Array<string>;
    groups?: Array<{
      label?: string;
      items?: Array<string>;
      _key: string;
    }>;
    _key: string;
  }>;
  conceptual?: {
    heading?: string;
    groups?: Array<{
      icon?: string;
      title?: string;
      note?: string;
      subgroups?: Array<{
        label?: string;
        items?: Array<string>;
        _key: string;
      }>;
      _key: string;
    }>;
  };
};

export type HubSettings = {
  _id: string;
  _type: 'hubSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  familyHandbook?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: 'file';
  };
  coopHoursGoal?: number;
  familyCount?: number;
  pastFundraisingTotals?: Array<{
    yearLabel?: string;
    amount?: number;
    _key: string;
  }>;
  budgetSheetId?: string;
  calendarFeedUrl?: string;
  googleCalendarId?: string;
  showDirectoryMap?: boolean;
};

export type HubStore = {
  _id: string;
  _type: 'hubStore';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  storeUrl?: string;
  storeHeadline?: string;
  storeTagline?: string;
  storeProducts?: Array<{
    title?: string;
    price?: string;
    url?: string;
    photo?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
    image?: string;
    _key: string;
  }>;
};

export type HubDelights = {
  _id: string;
  _type: 'hubDelights';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  funDays?: Array<{
    date?: string;
    label?: string;
    _key: string;
  }>;
  giggles?: Array<{
    setup?: string;
    punchline?: string;
    _key: string;
  }>;
};

export type LinkHealth = {
  _id: string;
  _type: 'linkHealth';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  checkedAt?: string;
  allOk?: boolean;
  summary?: string;
  results?: Array<{
    label?: string;
    ok?: boolean;
    note?: string;
    url?: string;
    _key: string;
  }>;
};

export type HubHints = {
  _id: string;
  _type: 'hubHints';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  enabled?: boolean;
  hints?: Array<{
    id?: 'directory-map' | 'calendar-filters';
    enabled?: boolean;
    text?: string;
    _key: string;
  }>;
};

export type HubTour = {
  _id: string;
  _type: 'hubTour';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  enabled?: boolean;
  version?: string;
  welcomeTitle?: string;
  welcomeBody?: string;
  navigateTitle?: string;
  navigateBody?: string;
  classesTitle?: string;
  classesBody?: string;
  helperTitle?: string;
  helperBody?: string;
  updatesTitle?: string;
  updatesBody?: string;
  moneyTitle?: string;
  moneyBody?: string;
  searchTitle?: string;
  searchBody?: string;
  helpTitle?: string;
  helpBody?: string;
};

export type HubPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'hubPage';
};

export type HubNavMenu = {
  _id: string;
  _type: 'hubNavMenu';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  groups?: Array<{
    label?: string;
    accent?: 'sky' | 'amber' | 'green' | 'orange';
    links?: Array<
      | {
          target?:
            | '/family-hub/twos-threes'
            | '/family-hub/pre-k'
            | '/family-hub/updates'
            | '/family-hub/calendar'
            | '/family-hub/getting-started'
            | '/family-hub/super-helper'
            | '/family-hub/documents'
            | '/family-hub/health'
            | '/family-hub/tuition'
            | '/family-hub/fundraising'
            | '/family-hub/directory'
            | '/family-hub/coop-jobs'
            | '/family-hub/celebrations'
            | 'https://store.westchesterpreschool.org/';
          label?: string;
          hidden?: boolean;
          _type: 'builtinLink';
          _key: string;
        }
      | {
          page?: HubPageReference;
          label?: string;
          _type: 'pageLink';
          _key: string;
        }
      | {
          label?: string;
          url?: string;
          icon?:
            | 'arrow-right'
            | 'award'
            | 'baby'
            | 'banknote'
            | 'bell'
            | 'blocks'
            | 'book-open'
            | 'building-2'
            | 'cake'
            | 'calculator'
            | 'calendar-days'
            | 'camera'
            | 'check'
            | 'circle-dollar-sign'
            | 'clipboard-list'
            | 'clock'
            | 'coins'
            | 'contact'
            | 'door-open'
            | 'dumbbell'
            | 'egg'
            | 'eye'
            | 'file-check'
            | 'file-pen'
            | 'file-text'
            | 'flower'
            | 'folder'
            | 'folder-open'
            | 'gift'
            | 'graduation-cap'
            | 'hand'
            | 'hand-heart'
            | 'heart'
            | 'heart-handshake'
            | 'heart-pulse'
            | 'house'
            | 'image'
            | 'info'
            | 'languages'
            | 'leaf'
            | 'list'
            | 'lock'
            | 'mail'
            | 'map-pin'
            | 'megaphone'
            | 'message-circle'
            | 'microscope'
            | 'moon'
            | 'newspaper'
            | 'notebook-pen'
            | 'palette'
            | 'party-popper'
            | 'pencil'
            | 'phone'
            | 'piggy-bank'
            | 'puzzle'
            | 'scale'
            | 'school'
            | 'send'
            | 'shield-check'
            | 'shopping-bag'
            | 'snowflake'
            | 'sparkles'
            | 'sprout'
            | 'star'
            | 'sun'
            | 'tent'
            | 'trees'
            | 'trending-down'
            | 'users';
          _type: 'externalLink';
          _key: string;
        }
    >;
    _type: 'navGroup';
    _key: string;
  }>;
};

export type HubPage = {
  _id: string;
  _type: 'hubPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  hubKey?:
    | 'home'
    | 'calendar'
    | 'coop-jobs'
    | 'documents'
    | 'tuition'
    | 'updates'
    | 'fundraising'
    | 'health'
    | 'directory'
    | 'twos-threes'
    | 'pre-k';
  slug?: string;
  navIcon?:
    | 'arrow-right'
    | 'award'
    | 'baby'
    | 'banknote'
    | 'bell'
    | 'blocks'
    | 'book-open'
    | 'building-2'
    | 'cake'
    | 'calculator'
    | 'calendar-days'
    | 'camera'
    | 'check'
    | 'circle-dollar-sign'
    | 'clipboard-list'
    | 'clock'
    | 'coins'
    | 'contact'
    | 'door-open'
    | 'dumbbell'
    | 'egg'
    | 'eye'
    | 'file-check'
    | 'file-pen'
    | 'file-text'
    | 'flower'
    | 'folder'
    | 'folder-open'
    | 'gift'
    | 'graduation-cap'
    | 'hand'
    | 'hand-heart'
    | 'heart'
    | 'heart-handshake'
    | 'heart-pulse'
    | 'house'
    | 'image'
    | 'info'
    | 'languages'
    | 'leaf'
    | 'list'
    | 'lock'
    | 'mail'
    | 'map-pin'
    | 'megaphone'
    | 'message-circle'
    | 'microscope'
    | 'moon'
    | 'newspaper'
    | 'notebook-pen'
    | 'palette'
    | 'party-popper'
    | 'pencil'
    | 'phone'
    | 'piggy-bank'
    | 'puzzle'
    | 'scale'
    | 'school'
    | 'send'
    | 'shield-check'
    | 'shopping-bag'
    | 'snowflake'
    | 'sparkles'
    | 'sprout'
    | 'star'
    | 'sun'
    | 'tent'
    | 'trees'
    | 'trending-down'
    | 'users';
  archived?: boolean;
  heading?: string;
  intro?: string;
  handbookFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: 'file';
  };
  sections?: Array<
    | ({
        _key: string;
      } & ProseSection)
    | ({
        _key: string;
      } & CardGridSection)
    | ({
        _key: string;
      } & StatBandSection)
    | ({
        _key: string;
      } & CtaSection)
    | ({
        _key: string;
      } & FaqSection)
    | ({
        _key: string;
      } & ScheduleSection)
    | ({
        _key: string;
      } & StepListSection)
    | ({
        _key: string;
      } & CompareSection)
    | ({
        _key: string;
      } & TabsSection)
    | ({
        _key: string;
      } & AccordionSection)
    | ({
        _key: string;
      } & QuickFactsSection)
    | ({
        _key: string;
      } & PullQuoteSection)
    | ({
        _key: string;
      } & VideoSection)
    | ({
        _key: string;
      } & MapSection)
    | ({
        _key: string;
      } & CountdownSection)
    | ({
        _key: string;
      } & GallerySection)
    | ({
        _key: string;
      } & StoryTimelineSection)
    | ({
        _key: string;
      } & SplitMediaSection)
    | ({
        _key: string;
      } & FormSection)
  >;
  publishAt?: string;
};

export type SiteMicrocopy = {
  _id: string;
  _type: 'siteMicrocopy';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  thanksEyebrow?: string;
  thanksTitle?: string;
  thanksLead?: string;
  thanksNote?: string;
  tourThanksEyebrow?: string;
  tourThanksLead?: string;
  tourThanksNote?: string;
  notFoundChip?: string;
  notFoundHeading?: string;
  notFoundBody?: string;
  footerSignOff?: string;
};

export type CoopGuidance = {
  _id: string;
  _type: 'coopGuidance';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  principles?: Array<{
    icon?:
      | 'arrow-right'
      | 'award'
      | 'baby'
      | 'scale'
      | 'bell'
      | 'building-2'
      | 'blocks'
      | 'cake'
      | 'calculator'
      | 'calendar-days'
      | 'camera'
      | 'hand-heart'
      | 'banknote'
      | 'file-check'
      | 'check'
      | 'clipboard-list'
      | 'clock'
      | 'coins'
      | 'contact'
      | 'file-text'
      | 'circle-dollar-sign'
      | 'dumbbell'
      | 'egg'
      | 'mail'
      | 'eye'
      | 'file-pen'
      | 'flower'
      | 'folder'
      | 'gift'
      | 'graduation-cap'
      | 'hand'
      | 'heart-handshake'
      | 'heart'
      | 'heart-pulse'
      | 'house'
      | 'info'
      | 'languages'
      | 'leaf'
      | 'list'
      | 'lock'
      | 'map-pin'
      | 'megaphone'
      | 'microscope'
      | 'moon'
      | 'newspaper'
      | 'notebook-pen'
      | 'book-open'
      | 'door-open'
      | 'folder-open'
      | 'palette'
      | 'send'
      | 'party-popper'
      | 'pencil'
      | 'users'
      | 'phone'
      | 'image'
      | 'piggy-bank'
      | 'puzzle'
      | 'school'
      | 'shield-check'
      | 'shopping-bag'
      | 'snowflake'
      | 'sparkles'
      | 'message-circle'
      | 'sprout'
      | 'star'
      | 'sun'
      | 'tent'
      | 'trees'
      | 'trending-down';
    title?: string;
    body?: string;
    _type: 'principle';
    _key: string;
  }>;
  teacherAsks?: Array<string>;
  repAsks?: Array<string>;
};

export type OperatingBudget = {
  _id: string;
  _type: 'operatingBudget';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  year?: string;
  enrollment?: string;
  netNote?: string;
  source?: string;
  groups?: Array<{
    label?: string;
    kind?: 'revenue' | 'expense';
    icon?:
      'circle-dollar-sign' | 'piggy-bank' | 'hand-heart' | 'building-2' | 'book-open' | 'coins';
    lines?: Array<{
      label?: string;
      now?: number;
      was?: number;
      note?: string;
      _type: 'budgetLine';
      _key: string;
    }>;
    _type: 'budgetGroup';
    _key: string;
  }>;
};

export type FeeSchedule = {
  _id: string;
  _type: 'feeSchedule';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  registrationFee?: string;
  registrationNote?: string;
  registrationPayId?: string;
  participationFee?: string;
  participationNote?: string;
  participationPayId?: string;
  annualAdjustmentNote?: string;
  studentFeeBands?: Array<{
    label?: string;
    amount?: string;
    payId?: string;
    _key: string;
  }>;
  paymentTerms?: Array<{
    icon?:
      | 'arrow-right'
      | 'award'
      | 'baby'
      | 'scale'
      | 'bell'
      | 'building-2'
      | 'blocks'
      | 'cake'
      | 'calculator'
      | 'calendar-days'
      | 'camera'
      | 'hand-heart'
      | 'banknote'
      | 'file-check'
      | 'check'
      | 'clipboard-list'
      | 'clock'
      | 'coins'
      | 'contact'
      | 'file-text'
      | 'circle-dollar-sign'
      | 'dumbbell'
      | 'egg'
      | 'mail'
      | 'eye'
      | 'file-pen'
      | 'flower'
      | 'folder'
      | 'gift'
      | 'graduation-cap'
      | 'hand'
      | 'heart-handshake'
      | 'heart'
      | 'heart-pulse'
      | 'house'
      | 'info'
      | 'languages'
      | 'leaf'
      | 'list'
      | 'lock'
      | 'map-pin'
      | 'megaphone'
      | 'microscope'
      | 'moon'
      | 'newspaper'
      | 'notebook-pen'
      | 'book-open'
      | 'door-open'
      | 'folder-open'
      | 'palette'
      | 'send'
      | 'party-popper'
      | 'pencil'
      | 'users'
      | 'phone'
      | 'image'
      | 'piggy-bank'
      | 'puzzle'
      | 'school'
      | 'shield-check'
      | 'shopping-bag'
      | 'snowflake'
      | 'sparkles'
      | 'message-circle'
      | 'sprout'
      | 'star'
      | 'sun'
      | 'tent'
      | 'trees'
      | 'trending-down';
    question?: string;
    answer?: string;
    _key: string;
  }>;
};

export type SiteSettings = {
  _id: string;
  _type: 'siteSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  shortName?: string;
  founded?: number;
  tagline?: string;
  url?: string;
  logoOverride?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  season?: 'auto' | 'fall' | 'winter' | 'spring' | 'summer' | 'off';
  phone?: string;
  emailGeneral?: string;
  emailAdmin?: string;
  emailTreasurer?: string;
  showPhone?: boolean;
  showEmail?: boolean;
  street?: string;
  city?: string;
  state?: string;
  zip?: string;
  parkingNote?: string;
  schoolYearLabel?: string;
  enrolling?: boolean;
  enrollmentMode?: 'open' | 'waitlist' | 'closed';
  enrollmentDeadline?: string;
  openingHours?: Array<{
    days?: Array<string>;
    opens?: string;
    closes?: string;
    _key: string;
  }>;
  closureStatement?: string;
  yearStart?: string;
  yearEnd?: string;
  firstDay?: string;
  availabilitySheetId?: string;
  facebook?: string;
  instagram?: string;
  showSocials?: boolean;
  googleRating?: string;
  googleReviews?: number;
  googleUrl?: string;
  license?: string;
  licenseAuthority?: string;
};

export type PhotoAlbumReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'photoAlbum';
};

export type InstagramSection = {
  _type: 'instagramSection';
  header?: SectionHeader;
  fallbackAlbum?: PhotoAlbumReference;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type AlbumSection = {
  _type: 'albumSection';
  header?: SectionHeader;
  album?: PhotoAlbumReference;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type PhotoAlbum = {
  _id: string;
  _type: 'photoAlbum';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  photos?: Array<
    {
      _key: string;
    } & FigureImage
  >;
};

export type DownloadsSection = {
  _type: 'downloadsSection';
  header?: SectionHeader;
  category?: 'all' | 'handbook' | 'calendar' | 'forms' | 'other';
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type JobsSection = {
  _type: 'jobsSection';
  header?: SectionHeader;
  emptyMessage?: string;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type CampaignSection = {
  _type: 'campaignSection';
  header?: SectionHeader;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type LogoStripSection = {
  _type: 'logoStripSection';
  header?: SectionHeader;
  source?: 'partners' | 'credentials';
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type BoardMembersSection = {
  _type: 'boardMembersSection';
  header?: SectionHeader;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type ProgramCardsSection = {
  _type: 'programCardsSection';
  header?: SectionHeader;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type ContactDetailsSection = {
  _type: 'contactDetailsSection';
  reachHeading?: string;
  visitHeading?: string;
  showParking?: boolean;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type NoticeBarSection = {
  _type: 'noticeBarSection';
  text?: string;
  linkLabel?: string;
  linkType?: 'page' | 'url';
  page?: PageReference;
  url?: string;
};

export type ReviewFormSection = {
  _type: 'reviewFormSection';
  header?: SectionHeader;
  buttonLabel?: string;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type NewsletterSignupSection = {
  _type: 'newsletterSignupSection';
  header?: SectionHeader;
  askName?: boolean;
  buttonLabel?: string;
  successMessage?: string;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type FormSection = {
  _type: 'formSection';
  header?: SectionHeader;
  topic?: string;
  variant?: 'general' | 'enroll' | 'waitlist' | 'tour' | 'teach';
  fields?: Array<
    {
      _key: string;
    } & FormField
  >;
  recipientNote?: string;
  showPhone?: boolean;
  buttonLabel?: string;
  successMessage?: string;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type UpcomingEventsSection = {
  _type: 'upcomingEventsSection';
  header?: SectionHeader;
  limit?: 3 | 4 | 6;
  linkLabel?: string;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type LatestPostsSection = {
  _type: 'latestPostsSection';
  header?: SectionHeader;
  limit?: 2 | 3 | 4;
  linkLabel?: string;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type SplitMediaSection = {
  _type: 'splitMediaSection';
  header?: SectionHeader;
  rows?: Array<{
    image?: RowImage;
    alt?: string;
    eyebrow?: string;
    title?: string;
    body?: string;
    linkLabel?: string;
    linkUrl?: string;
    _type: 'row';
    _key: string;
  }>;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type StoryTimelineSection = {
  _type: 'storyTimelineSection';
  header?: SectionHeader;
  moments?: Array<{
    time?: string;
    title?: string;
    body?: string;
    photos?: Array<
      {
        _key: string;
      } & FigureImage
    >;
    _type: 'moment';
    _key: string;
  }>;
  footnote?: string;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type GallerySection = {
  _type: 'gallerySection';
  header?: SectionHeader;
  photos?: Array<
    {
      _key: string;
    } & FigureImage
  >;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type CountdownSection = {
  _type: 'countdownSection';
  header?: SectionHeader;
  targetDate?: string;
  completedMessage?: string;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type MapSection = {
  _type: 'mapSection';
  header?: SectionHeader;
  address?: string;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type VideoSection = {
  _type: 'videoSection';
  header?: SectionHeader;
  videoUrl?: string;
  thumbnail?: FigureImage;
  caption?: string;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type PullQuoteSection = {
  _type: 'pullQuoteSection';
  quote?: string;
  attribution?: string;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type QuickFactsSection = {
  _type: 'quickFactsSection';
  header?: SectionHeader;
  facts?: Array<{
    icon?:
      | 'arrow-right'
      | 'award'
      | 'baby'
      | 'scale'
      | 'bell'
      | 'building-2'
      | 'blocks'
      | 'cake'
      | 'calculator'
      | 'calendar-days'
      | 'camera'
      | 'hand-heart'
      | 'banknote'
      | 'file-check'
      | 'check'
      | 'clipboard-list'
      | 'clock'
      | 'coins'
      | 'contact'
      | 'file-text'
      | 'circle-dollar-sign'
      | 'dumbbell'
      | 'egg'
      | 'mail'
      | 'eye'
      | 'file-pen'
      | 'flower'
      | 'folder'
      | 'gift'
      | 'graduation-cap'
      | 'hand'
      | 'heart-handshake'
      | 'heart'
      | 'heart-pulse'
      | 'house'
      | 'info'
      | 'languages'
      | 'leaf'
      | 'list'
      | 'lock'
      | 'map-pin'
      | 'megaphone'
      | 'microscope'
      | 'moon'
      | 'newspaper'
      | 'notebook-pen'
      | 'book-open'
      | 'door-open'
      | 'folder-open'
      | 'palette'
      | 'send'
      | 'party-popper'
      | 'pencil'
      | 'users'
      | 'phone'
      | 'image'
      | 'piggy-bank'
      | 'puzzle'
      | 'school'
      | 'shield-check'
      | 'shopping-bag'
      | 'snowflake'
      | 'sparkles'
      | 'message-circle'
      | 'sprout'
      | 'star'
      | 'sun'
      | 'tent'
      | 'trees'
      | 'trending-down';
    value?: string;
    label?: string;
    _type: 'fact';
    _key: string;
  }>;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type AccordionSection = {
  _type: 'accordionSection';
  header?: SectionHeader;
  items?: Array<{
    label?: string;
    body?: InlineText;
    _type: 'row';
    _key: string;
  }>;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type TabsSection = {
  _type: 'tabsSection';
  header?: SectionHeader;
  tabs?: Array<{
    label?: string;
    body?: InlineText;
    _type: 'tab';
    _key: string;
  }>;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type CompareSection = {
  _type: 'compareSection';
  header?: SectionHeader;
  wcpLabel?: string;
  typicalLabel?: string;
  rows?: Array<{
    feature?: string;
    wcp?: string;
    typical?: string;
    _type: 'row';
    _key: string;
  }>;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type StepListSection = {
  _type: 'stepListSection';
  header?: SectionHeader;
  steps?: Array<{
    title?: string;
    body?: string;
    note?: string;
    _type: 'step';
    _key: string;
  }>;
  footnote?: string;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type ScheduleSection = {
  _type: 'scheduleSection';
  header?: SectionHeader;
  intro?: string;
  entries?: Array<{
    time?: string;
    timePm?: string;
    title?: string;
    description?: string;
    _type: 'entry';
    _key: string;
  }>;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type EnrollmentCtaSection = {
  _type: 'enrollmentCtaSection';
  linkType?: 'page' | 'url';
  page?: PageReference;
  url?: string;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type TuitionCalculatorSection = {
  _type: 'tuitionCalculatorSection';
  header?: SectionHeader;
  note?: string;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type TuitionTableSection = {
  _type: 'tuitionTableSection';
  header?: SectionHeader;
  caption?: string;
  callout?: Callout;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type SchoolYearSection = {
  _type: 'schoolYearSection';
  header?: SectionHeader;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type FaqSection = {
  _type: 'faqSection';
  header?: SectionHeader;
  source?: 'category' | 'inline';
  category?: 'coop' | 'classes' | 'enrollment' | 'about' | 'donation';
  inlineItems?: Array<{
    question?: string;
    answer?: BlockContent;
    _type: 'qa';
    _key: string;
  }>;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type ClassReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'class';
};

export type ClassCardsSection = {
  _type: 'classCardsSection';
  header?: SectionHeader;
  classes?: Array<
    {
      _key: string;
    } & ClassReference
  >;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type TeacherSection = {
  _type: 'teacherSection';
  header?: SectionHeader;
  staff?: Array<
    {
      _key: string;
    } & StaffReference
  >;
  callout?: Callout;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type TestimonialReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'testimonial';
};

export type TestimonialSection = {
  _type: 'testimonialSection';
  header?: SectionHeader;
  source?: 'featured' | 'all' | 'tag' | 'manual';
  tag?: 'twos' | 'threes' | 'prek' | 'alumni';
  limit?: number;
  manualItems?: Array<
    {
      _key: string;
    } & TestimonialReference
  >;
  layout?: 'grid' | 'wall';
  confetti?: boolean;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type CtaSection = {
  _type: 'ctaSection';
  title?: string;
  lead?: string;
  tone?: 'navy' | 'cream';
  actions?: Array<
    {
      _key: string;
    } & ActionButton
  >;
  note?: InlineText;
};

export type StatBandSection = {
  _type: 'statBandSection';
  ariaLabel?: string;
  stats?: Array<{
    value?: string;
    prefix?: string;
    suffix?: string;
    label?: string;
    note?: string;
    _type: 'stat';
    _key: string;
  }>;
};

export type CardGridSection = {
  _type: 'cardGridSection';
  header?: SectionHeader;
  cards?: Array<
    {
      _key: string;
    } & IconCard
  >;
  columns?: 2 | 3 | 4;
  layout?: 'card' | 'compactIcon';
  callout?: Callout;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type ProseSection = {
  _type: 'proseSection';
  header?: SectionHeader;
  body?: RichProse;
  callout?: Callout;
  narrow?: boolean;
  background?: 'white' | 'grey' | 'cream' | 'navy';
  compact?: boolean;
};

export type HeroObject = {
  _type: 'heroObject';
  eyebrow?: string;
  title?: string;
  accentWord?: string;
  accentColor?: 'amber' | 'orange' | 'sky' | 'green';
  lead?: string;
  actions?: Array<
    {
      _key: string;
    } & ActionButton
  >;
  height?: 'tall' | 'medium';
  mediaType?: 'none' | 'image' | 'video';
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  imageAlt?: string;
  videoFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: 'file';
  };
  videoWebm?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: 'file';
  };
};

export type NavGroup = {
  _type: 'navGroup';
  label?: string;
  children?: Array<
    {
      _key: string;
    } & NavLink
  >;
};

export type NavLink = {
  _type: 'navLink';
  label?: string;
  linkType?: 'page' | 'url';
  page?: PageReference;
  url?: string;
};

export type Callout = {
  _type: 'callout';
  tone?: 'sky' | 'warm';
  body?: InlineText;
};

export type ActionButton = {
  _type: 'actionButton';
  label?: string;
  style?: 'accent' | 'outline-white' | 'primary' | 'outline';
  linkType?: 'page' | 'url';
  page?: PageReference;
  url?: string;
};

export type Page = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: string;
  hero?: HeroObject;
  sections?: Array<
    | ({
        _key: string;
      } & ProseSection)
    | ({
        _key: string;
      } & CardGridSection)
    | ({
        _key: string;
      } & StatBandSection)
    | ({
        _key: string;
      } & CtaSection)
    | ({
        _key: string;
      } & TestimonialSection)
    | ({
        _key: string;
      } & TeacherSection)
    | ({
        _key: string;
      } & ClassCardsSection)
    | ({
        _key: string;
      } & FaqSection)
    | ({
        _key: string;
      } & SchoolYearSection)
    | ({
        _key: string;
      } & TuitionTableSection)
    | ({
        _key: string;
      } & TuitionCalculatorSection)
    | ({
        _key: string;
      } & EnrollmentCtaSection)
    | ({
        _key: string;
      } & ScheduleSection)
    | ({
        _key: string;
      } & StepListSection)
    | ({
        _key: string;
      } & CompareSection)
    | ({
        _key: string;
      } & TabsSection)
    | ({
        _key: string;
      } & AccordionSection)
    | ({
        _key: string;
      } & QuickFactsSection)
    | ({
        _key: string;
      } & PullQuoteSection)
    | ({
        _key: string;
      } & VideoSection)
    | ({
        _key: string;
      } & MapSection)
    | ({
        _key: string;
      } & CountdownSection)
    | ({
        _key: string;
      } & GallerySection)
    | ({
        _key: string;
      } & StoryTimelineSection)
    | ({
        _key: string;
      } & SplitMediaSection)
    | ({
        _key: string;
      } & LatestPostsSection)
    | ({
        _key: string;
      } & UpcomingEventsSection)
    | ({
        _key: string;
      } & FormSection)
    | ({
        _key: string;
      } & NewsletterSignupSection)
    | ({
        _key: string;
      } & ReviewFormSection)
    | ({
        _key: string;
      } & NoticeBarSection)
    | ({
        _key: string;
      } & ContactDetailsSection)
    | ({
        _key: string;
      } & ProgramCardsSection)
    | ({
        _key: string;
      } & BoardMembersSection)
    | ({
        _key: string;
      } & LogoStripSection)
    | ({
        _key: string;
      } & CampaignSection)
    | ({
        _key: string;
      } & JobsSection)
    | ({
        _key: string;
      } & DownloadsSection)
    | ({
        _key: string;
      } & AlbumSection)
    | ({
        _key: string;
      } & InstagramSection)
  >;
  archived?: boolean;
  seoPreview?: string;
  seoTitle?: string;
  seoDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  hideFromSearch?: boolean;
  publishAt?: string;
};

export type SectionHeader = {
  _type: 'sectionHeader';
  eyebrow?: string;
  title?: string;
  lead?: string;
  align?: 'center' | 'left';
};

export type InlineText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: 'span';
    _key: string;
  }>;
  style?: 'normal';
  listItem?: never;
  markDefs?: Array<{
    href?: string;
    _type: 'link';
    _key: string;
  }>;
  level?: number;
  _type: 'block';
  _key: string;
}>;

export type FormField = {
  _type: 'formField';
  label?: string;
  kind?: 'text' | 'email' | 'phone' | 'textarea' | 'select' | 'checkbox';
  options?: Array<string>;
  required?: boolean;
};

export type IconCard = {
  _type: 'iconCard';
  icon?:
    | 'arrow-right'
    | 'award'
    | 'baby'
    | 'scale'
    | 'bell'
    | 'building-2'
    | 'blocks'
    | 'cake'
    | 'calculator'
    | 'calendar-days'
    | 'camera'
    | 'hand-heart'
    | 'banknote'
    | 'file-check'
    | 'check'
    | 'clipboard-list'
    | 'clock'
    | 'coins'
    | 'contact'
    | 'file-text'
    | 'circle-dollar-sign'
    | 'dumbbell'
    | 'egg'
    | 'mail'
    | 'eye'
    | 'file-pen'
    | 'flower'
    | 'folder'
    | 'gift'
    | 'graduation-cap'
    | 'hand'
    | 'heart-handshake'
    | 'heart'
    | 'heart-pulse'
    | 'house'
    | 'info'
    | 'languages'
    | 'leaf'
    | 'list'
    | 'lock'
    | 'map-pin'
    | 'megaphone'
    | 'microscope'
    | 'moon'
    | 'newspaper'
    | 'notebook-pen'
    | 'book-open'
    | 'door-open'
    | 'folder-open'
    | 'palette'
    | 'send'
    | 'party-popper'
    | 'pencil'
    | 'users'
    | 'phone'
    | 'image'
    | 'piggy-bank'
    | 'puzzle'
    | 'school'
    | 'shield-check'
    | 'shopping-bag'
    | 'snowflake'
    | 'sparkles'
    | 'message-circle'
    | 'sprout'
    | 'star'
    | 'sun'
    | 'tent'
    | 'trees'
    | 'trending-down';
  chip?: 'sky' | 'orange' | 'amber' | 'green' | 'navy';
  title?: string;
  statValue?: string;
  body?: string;
  href?: string;
  linkLabel?: string;
};

export type VenueReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'venue';
};

export type Event = {
  _id: string;
  _type: 'event';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  startDate?: string;
  endDate?: string;
  allDay?: boolean;
  recurrence?: 'none' | 'weekly' | 'monthly';
  recurrenceEnd?: string;
  venue?: VenueReference;
  location?: string;
  category?: 'openHouse' | 'community' | 'fundraiser' | 'closure' | 'other';
  description?: string;
  ctaLabel?: string;
  ctaUrl?: string;
};

export type Venue = {
  _id: string;
  _type: 'venue';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  address?: string;
  note?: string;
  isPrimary?: boolean;
};

export type SignupSheet = {
  _id: string;
  _type: 'signupSheet';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  kind?: 'signup' | 'rsvp';
  eventDate?: string;
  slots?: Array<{
    label?: string;
    detail?: string;
    capacity?: number;
    _type: 'slot';
    _key: string;
  }>;
  open?: boolean;
};

export type MediaTag = {
  _id: string;
  _type: 'media.tag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | RowImage
  | SanityFileAssetReference
  | FileAttachmentFile
  | SignupSheetReference
  | SignupEntry
  | TeacherNote
  | SanityImageCrop
  | SanityImageHotspot
  | BlockContent
  | HubDocument
  | Celebration
  | Update
  | EventReference
  | PostBody
  | Slug
  | Resource
  | JobPosting
  | RichProse
  | Campaign
  | Credential
  | FigureImage
  | Partner
  | BoardMember
  | Program
  | HoursLog
  | DirectoryEntryReference
  | RoleHolder
  | DirectoryEntry
  | Geopoint
  | CoopRole
  | TrashedItem
  | PhotoSubmission
  | TestimonialSubmission
  | Subscriber
  | Submission
  | PageReference
  | Announcement
  | Redirect
  | NewsletterIssue
  | StaffReference
  | Post
  | SectionPreset
  | LegalPage
  | SchoolYearEvent
  | FaqItem
  | Testimonial
  | Class
  | Staff
  | PresidentNote
  | ClosureAlert
  | Navigation
  | SupplyList
  | CurriculumGuide
  | HubSettings
  | HubStore
  | HubDelights
  | LinkHealth
  | HubHints
  | HubTour
  | HubPageReference
  | HubNavMenu
  | HubPage
  | SiteMicrocopy
  | CoopGuidance
  | OperatingBudget
  | FeeSchedule
  | SiteSettings
  | PhotoAlbumReference
  | InstagramSection
  | AlbumSection
  | PhotoAlbum
  | DownloadsSection
  | JobsSection
  | CampaignSection
  | LogoStripSection
  | BoardMembersSection
  | ProgramCardsSection
  | ContactDetailsSection
  | NoticeBarSection
  | ReviewFormSection
  | NewsletterSignupSection
  | FormSection
  | UpcomingEventsSection
  | LatestPostsSection
  | SplitMediaSection
  | StoryTimelineSection
  | GallerySection
  | CountdownSection
  | MapSection
  | VideoSection
  | PullQuoteSection
  | QuickFactsSection
  | AccordionSection
  | TabsSection
  | CompareSection
  | StepListSection
  | ScheduleSection
  | EnrollmentCtaSection
  | TuitionCalculatorSection
  | TuitionTableSection
  | SchoolYearSection
  | FaqSection
  | ClassReference
  | ClassCardsSection
  | TeacherSection
  | TestimonialReference
  | TestimonialSection
  | CtaSection
  | StatBandSection
  | CardGridSection
  | ProseSection
  | HeroObject
  | NavGroup
  | NavLink
  | Callout
  | ActionButton
  | Page
  | SectionHeader
  | InlineText
  | FormField
  | IconCard
  | VenueReference
  | Event
  | Venue
  | SignupSheet
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset;
